const root = document.querySelector('#app');
let theme = 'sun', screen = 'map', muted = true, question = 0, hearts = 3, correct = 0, selected = null, feedback = '', filter = '', audioContext;
function preventGamePinchZoom(event){if(screen!=='map')event.preventDefault();}
document.addEventListener('gesturestart',preventGamePinchZoom,{passive:false});
document.addEventListener('gesturechange',preventGamePinchZoom,{passive:false});
document.addEventListener('touchmove',event=>{if(screen!=='map'&&event.touches.length>1)event.preventDefault();},{passive:false});
const words = [
 {en:'Turtle',es:'Tortuga',kind:'turtle'}, {en:'Octopus',es:'Pulpo',kind:'octopus'},
 {en:'Fish',es:'Pez',kind:'fish'}, {en:'Crab',es:'Cangrejo',kind:'crab'}
];
function animal(kind, cls='') {
 const shapes = {
 turtle:'<ellipse cx="63" cy="124" rx="20" ry="13" fill="#69c38a" transform="rotate(-30 63 124)"/><ellipse cx="144" cy="125" rx="20" ry="13" fill="#69c38a"/><ellipse cx="101" cy="99" rx="53" ry="39" fill="#257f68"/><ellipse cx="99" cy="91" rx="47" ry="32" fill="#77c982"/><path d="M80 71 111 69 126 89 111 111 81 108 68 90Z" fill="#a6df89" stroke="#4caa76" stroke-width="4"/><ellipse cx="155" cy="81" rx="30" ry="27" fill="#89d69b"/><circle cx="165" cy="76" r="5" fill="#203c48"/><circle cx="167" cy="74" r="1.5" fill="white"/><path d="M162 91q8 6 13-2" fill="none" stroke="#34755b" stroke-width="3"/>',
 octopus:'<path d="M60 109q-36 47-15 43 19-2 29-27-8 37 9 32 10-1 17-32 5 42 19 30 8-5 6-29 23 38 36 21 5-8-20-39" fill="#b784e6" stroke="#9966cd" stroke-width="4"/><path d="M53 104Q45 35 100 35t47 69q-40 35-94 0" fill="#cc9ff3"/><ellipse cx="80" cy="52" rx="16" ry="7" fill="#e6cafa" transform="rotate(-23 80 52)"/><circle cx="80" cy="89" r="5" fill="#343052"/><circle cx="120" cy="89" r="5" fill="#343052"/><path d="M91 102q9 9 18 0" fill="none" stroke="#643d86" stroke-width="4"/><ellipse cx="67" cy="101" rx="9" ry="5" fill="#f1b3d2"/><ellipse cx="133" cy="101" rx="9" ry="5" fill="#f1b3d2"/>',
 fish:'<path d="m59 94-37-32v66Z" fill="#f6a543"/><path d="m91 65 13-28 27 34m-40 49 18 25 20-28" fill="#ee8c45"/><ellipse cx="109" cy="95" rx="58" ry="39" fill="#ffc366"/><path d="M95 62q-15 32 0 65m25-66q-15 32 0 65" fill="none" stroke="#fff0c8" stroke-width="13"/><circle cx="147" cy="86" r="5" fill="#343e4a"/><path d="M148 105q7 4 12-3" stroke="#b06e38" fill="none" stroke-width="3"/>',
 crab:'<path d="m68 114-28 17m28-28-37 2m97 9 29 17m-26-28 37 2" stroke="#e47a64" stroke-width="9" stroke-linecap="round"/><path d="m64 98-24-21m95 21 24-21" stroke="#e47a64" stroke-width="12"/><path d="M44 83Q8 81 23 43l14 18 17-15q13 30-10 37m111 0q37-2 22-40l-14 18-17-15q-13 30 9 37" fill="#ff9b79"/><ellipse cx="100" cy="106" rx="47" ry="30" fill="#ffad88"/><path d="m81 82-4-17m43 17 4-17" stroke="#ffad88" stroke-width="10"/><circle cx="77" cy="63" r="7" fill="#404453"/><circle cx="124" cy="63" r="7" fill="#404453"/><path d="M90 110q10 10 21 0" stroke="#b65c52" stroke-width="4" fill="none"/>'
 };
 return `<svg class="animal ${cls}" viewBox="0 0 200 180" role="img" aria-label="${words.find(w=>w.kind===kind)?.es||'Tortuga'}"><ellipse cx="102" cy="154" rx="62" ry="9" fill="#173c5412"/>${shapes[kind]||shapes.turtle}</svg>`;
}
function island(x,y,scale,label,number,kind,locked=false) {
 return `<g transform="translate(${x} ${y}) scale(${scale})"><ellipse cy="88" rx="120" ry="30" fill="#153f4915"/><path d="M-107 15Q-119 65-67 81L35 92Q110 74 108 22Z" fill="${theme==='sun'?'#c28b57':'#69519e'}"/><path d="M-104 24Q-105 68-53 74L30 83Q91 66 104 34" fill="none" stroke="${theme==='sun'?'#dda96c':'#9372b8'}" stroke-width="9"/><ellipse rx="112" ry="51" fill="${theme==='sun'?'#f4d9a0':'#bca1e9'}"/><ellipse cy="-6" rx="98" ry="43" fill="${locked?'#b9c9c4':theme==='sun'?'#85cda1':'#8ccef1'}"/><path d="m-67-7 22-55 25 55z" fill="${theme==='sun'?'#4e9f85':'#7281cd'}"/><path d="m-37-8 30-76 33 76z" fill="${theme==='sun'?'#65b38e':'#9497e1'}"/><path d="m-7-84-10 28 20-1z" fill="#e6f7e9"/><circle cx="51" cy="-12" r="23" fill="#ffffff70"/><text x="51" y="-3" text-anchor="middle" font-size="24">${locked?'🔒':kind}</text><text y="49" text-anchor="middle" fill="#25464f" font-size="15" font-weight="800">${number}. ${label}</text></g>`;
}
function mapArt() {return `<svg viewBox="0 0 1000 500" class="world" aria-label="Mapa de tres juegos: Encuentra, Conecta y Memoria"><path d="M184 325C265 370 282 140 408 185S592 359 680 272 768 115 854 125" fill="none" stroke="${theme==='sun'?'#fff9df':'#e5d6ff'}" stroke-width="9" stroke-linecap="round" stroke-dasharray="3 20"/>${island(410,174,1.22,'Encuentra',2,'★')}${island(677,278,.93,'Conecta',3,'',true)}${island(851,114,.8,'Memoria',4,'',true)}<g fill="${theme==='sun'?'#fff':'#eadbff'}" opacity=".7"><ellipse cx="115" cy="101" rx="54" ry="14"/><ellipse cx="135" cy="87" rx="29" ry="21"/><ellipse cx="817" cy="400" rx="65" ry="16"/><ellipse cx="796" cy="384" rx="30" ry="23"/></g></svg>`;}
function nav() {return `<aside class="sidebar"><a class="brand" href="#" data-action="map"><span class="brand-icon">✦</span><span>ENGLISH<small>QUEST</small></span></a><nav>${[['map','⌂','Aventura'],['dictionary','▤','Diccionario'],['collection','✧','Mis cartas']].map(([id,icon,label])=>`<button class="nav-item ${screen===id?'active':''}" data-action="${id}"><span>${icon}</span>${label}</button>`).join('')}</nav><div class="side-bottom"><button class="mini-mascot" data-ocean="mascot" aria-label="Saludar a Coral, tu mascota">${animal('turtle')}<strong>Soy Coral, tu compañera.<br>¡Tócame para saludar!</strong></button><button class="user" data-action="profile"><span class="avatar">👩🏽‍🚀</span><span>Ximena<small>Exploradora · Nivel 1</small></span><span>›</span></button></div></aside>`;}
function header(title,subtitle) {return `<header><div><p class="eyebrow">${subtitle}</p><h1>${title}</h1></div><div class="stats"><span class="stat">⭐ <b>${totalStars()}</b></span><button class="sound" data-action="sound" aria-label="${muted?'Activar':'Desactivar'} sonido">${muted?'♪ ×':'♪ ✓'}</button></div></header>`;}
function mapView(){return `${header('Tu próxima gran aventura','¡HOLA, XIMENA!')}<div class="map-layout"><section class="map-panel">${oceanScene()}<div class="map-heading"><span class="pill">${theme==='sun'?'MUNDO 01 · OCÉANO':'GALAXIA 01 · OCÉANO'}</span><h2>Un océano por descubrir</h2><p>Palabras nuevas, tesoros increíbles.</p></div><div class="floating-spark s1">✧</div><div class="floating-spark s2">✦</div>${mapArt()}<button class="level-hotspot" data-action="game" aria-label="Jugar nivel 2: Encuentra"><span>2</span><small>¡Vamos!</small></button><div class="map-footer"><span>✦ Explora · Juega · Descubre</span><span>3 juegos por isla</span></div></section><aside class="quest-panel"><span class="eyebrow">TU SIGUIENTE MISIÓN</span><div class="quest-picture">${animal('turtle')}<span class="picture-spark">✦</span></div><span class="pill pale">NIVEL 02</span><h2>Encuentra al animal</h2><p>Mira la palabra en inglés y descubre qué animal es.</p><div class="quest-meta"><span>♥ 3 vidas</span><span>✦ 4 palabras</span></div><button class="primary" data-action="game">¡A jugar! <span>→</span></button><div class="prize-teaser"><span>✧</span><div><b>Un nuevo amigo te espera</b><small>Completa el reto y descubre su carta.</small></div></div></aside></div><section class="categories"><div class="section-title"><h2>Más mundos para explorar</h2><span>Un universo de palabras</span></div><div class="category-row">${[['🐾','Animales','Mar, selva y mucho más'],['⚽','Deportes','¡Vamos a jugar!'],['🏡','Mi mundo','Casa, escuela y familia'],['🍓','Sabores y salidas','Comidas y aventuras']].map(([icon,name,description])=>`<button class="category" data-action="preview"><span>${icon}</span><div><b>${name}</b><small>${description}</small></div><span>›</span></button>`).join('')}</div></section>`;}
function gameView(){const word=words[question];return `${header('¿Quién se esconde aquí?','OCÉANO / ENCUENTRA')}<section class="game-panel"><div class="game-top"><button class="text-button" data-action="map">← Volver al mapa</button><span>Pregunta ${question+1} de 4</span><span class="hearts" aria-label="${hearts} vidas">${'♥'.repeat(hearts)}${'♡'.repeat(3-hearts)}</span></div><div class="progress"><span style="width:${question/4*100}%"></span></div><p class="instruction">Toca la imagen que corresponde a</p><h2 class="word">${word.en}</h2><div class="answers">${[...words].sort((a,b)=>['fish','turtle','crab','octopus'].indexOf(a.kind)-['fish','turtle','crab','octopus'].indexOf(b.kind)).map(w=>`<button class="answer ${selected===w.kind?(w.kind===word.kind?'right':'wrong'):''}" data-answer="${w.kind}" ${selected?'disabled':''} aria-label="${w.es}">${animal(w.kind)}<span>${selected?w.es:'●'}</span></button>`).join('')}</div><div class="feedback" aria-live="polite">${feedback||'Observa con calma. ¡Tú puedes!'}${selected&&selected!==words[question].kind?`<button class="primary small" data-action="next">${hearts===0?'Volver a intentarlo':question===3?'Ver mi premio':'Continuar'} →</button>`:''}</div><div class="practice-note">Vista previa · práctica sin reloj</div></section>`;}
function dictionaryLessons(){return islandLessons.filter((_,index)=>!isIslandLocked(oceanIslands[index]));}
function dictionaryView(){const lessons=dictionaryLessons();return `${header('Mi diccionario','CADA PALABRA ES UN DESCUBRIMIENTO')}<div class="dictionary-tools"><span class="pill">${lessons.length} ${lessons.length===1?'isla':'islas'} · ${lessons.reduce((sum,lesson)=>sum+lesson.words.length,0)} palabras</span><input id="search" type="search" placeholder="Buscar en inglés o español" aria-label="Buscar palabras" value="${filter.replaceAll('&','&amp;').replaceAll('"','&quot;').replaceAll('<','&lt;')}"></div><div class="word-grid" id="word-grid">${wordCards(lessons)}</div>`;}
function wordCards(lessons=dictionaryLessons()){return lessons.flatMap(lesson=>lesson.words.map(w=>({...w,topic:lesson.topic}))).filter(w=>(w.en+' '+w.es).toLocaleLowerCase().includes(filter.toLocaleLowerCase())).map(w=>`<article class="word-card"><div class="lesson-icon" aria-hidden="true">${w.icon}</div><h2>${w.en}</h2><p>${w.es}</p><span class="pill pale">${w.topic}</span></article>`).join('')||'<p>No hay palabras que coincidan.</p>';}
function collectionView(){return `${header('Pequeños grandes tesoros','MI COLECCIÓN')}<div class="collection-banner"><div><h2>Amigos del océano</h2><p>Una aventura. Cuatro nuevos amigos.</p></div><span class="pill">Colección de muestra</span></div><div class="word-grid">${words.map((w,i)=>`<button class="collect-card ${i>1?'uncollected':''}" data-action="${i>1?'preview':'flip'}"><span class="card-number">OCÉANO · 00${i+1}</span>${animal(w.kind)}<h2>${w.en}</h2><p>${w.es}</p><span class="card-rarity">${i>1?'POR DESCUBRIR':'✦ EXPLORADORA ✦'}</span><span class="card-back">${w.es}<small>${w.en}</small></span></button>`).join('')}</div>`;}
function profileView(){return `${header('¡Tu aventura te espera!','BIENVENIDA A ENGLISH QUEST')}<section class="profile-panel"><div class="profile-decoration">${animal('turtle')}</div><span class="eyebrow">ELIGE TU EXPLORADORA</span><button class="profile-avatar" data-action="select-profile">👩🏽‍🚀<span>Ximena</span><small>Tu mundo está lleno de sorpresas</small></button><button class="primary" data-action="map">Entrar a la aventura →</button><p>Vista previa del perfil · acceso sin PIN en este prototipo.</p></section>`;}
function rewardView(){return `${header('¡Una aventura increíble!','MISIÓN COMPLETADA')}<section class="reward-panel"><div class="confetti">✦ · ★ · ✧ · ★ · ✦</div><span class="pill">NUEVA CARTA</span><h2>¡Conociste a un nuevo amigo!</h2><div class="reward-card">${animal('turtle')}<h3>Turtle</h3><p>Tortuga</p><span>✦ AMIGOS DEL OCÉANO ✦</span></div><p>${correct} de 4 aciertos · ${correct===4?'⭐⭐⭐':correct>=2?'⭐⭐':'⭐'}</p><button class="primary" data-action="collection">Ver mi colección →</button><button class="text-button" data-action="map">Volver al mapa</button></section>`;}
let missionCollapsed = false;
let coinShopMessage='';
const COIN_REDEEM_PIN='2580';
const COIN_REDEMPTIONS_KEY='ximena-coin-redemptions-v1';
function pesosAccumulated(){return coinBalance/30;}
function coinRedemptions(){try{const list=JSON.parse(localStorage.getItem(COIN_REDEMPTIONS_KEY)||'[]');return Array.isArray(list)?list.filter(item=>Number.isSafeInteger(item.amount)&&item.amount>=100&&item.amount%100===0):[];}catch{return [];}}
function coinChestArt(){return `<div class="coin-treasure" aria-hidden="true"><i class="treasure-glow"></i><span class="treasure-spark spark-one">✦</span><span class="treasure-spark spark-two">✧</span><span class="treasure-spark spark-three">✦</span><svg viewBox="0 0 280 190"><defs><linearGradient id="chest-wood" x2="0" y2="1"><stop stop-color="#d29255"/><stop offset="1" stop-color="#9a4e31"/></linearGradient><linearGradient id="chest-gold" x2=".7" y2="1"><stop stop-color="#fff4b5"/><stop offset=".5" stop-color="#f7c65e"/><stop offset="1" stop-color="#dc922f"/></linearGradient></defs><ellipse cx="140" cy="166" rx="99" ry="13" fill="#185e631f"/><g class="treasure-chest"><path d="M57 94V66q0-36 37-36h92q37 0 37 36v28Z" fill="url(#chest-wood)" stroke="#85442f" stroke-width="4"/><path d="M62 66h156M62 82h156" stroke="#f3bd7d" stroke-width="3" opacity=".55"/><path d="M79 91V57q0-21 17-25m88 0q18 4 18 25v34" fill="none" stroke="url(#chest-gold)" stroke-width="13"/><path d="M57 88h166l-8 65q-2 12-15 12H80q-13 0-15-12Z" fill="url(#chest-wood)" stroke="#85442f" stroke-width="4"/><path d="M68 117h146m-143 23h140" stroke="#6f392a" opacity=".3" stroke-width="3"/><path d="m81 91 6 70m112-70-6 70" stroke="url(#chest-gold)" stroke-width="14"/><path d="M57 89h166v17H57Z" fill="url(#chest-gold)" stroke="#b77c32" stroke-width="2"/><rect x="123" y="96" width="34" height="34" rx="8" fill="url(#chest-gold)" stroke="#ad7234" stroke-width="2"/><path d="m140 104 4 7 8 1-6 5 1 8-7-4-7 4 1-8-6-5 8-1Z" fill="#a6682f"/><circle cx="87" cy="118" r="3" fill="#fff1b1"/><circle cx="193" cy="118" r="3" fill="#fff1b1"/></g><g class="treasure-floating-coin"><circle cx="139" cy="31" r="24" fill="url(#chest-gold)" stroke="#d79232" stroke-width="3"/><circle cx="139" cy="31" r="18" fill="none" stroke="#fff6c1" stroke-width="2"/><path d="m139 18 4 8 9 1-6 6 1 9-8-4-8 4 1-9-6-6 9-1Z" fill="#b97e29"/></g><g fill="url(#chest-gold)" stroke="#d79b3c" stroke-width="2"><ellipse cx="48" cy="158" rx="22" ry="8"/><ellipse cx="48" cy="152" rx="22" ry="8"/><ellipse cx="232" cy="159" rx="23" ry="8"/><ellipse cx="232" cy="153" rx="23" ry="8"/><ellipse cx="232" cy="147" rx="23" ry="8"/></g></svg></div>`;}
function coinShopView(){const eligible=Math.floor(coinBalance/3000)*100,history=coinRedemptions();return `${header('Canje de monedas','MIS RECOMPENSAS')}<section class="coin-shop">${coinChestArt()}<div class="coin-shop-balance">${goldCoinIcon()}<div><small>Monedas disponibles</small><strong>${coinBalance.toLocaleString('es-MX')}</strong></div></div><div class="coin-shop-cash"><small>Dinero acumulado</small><strong>${pesosAccumulated().toLocaleString('es-MX',{style:'currency',currency:'MXN'})}</strong></div>${eligible>=100?`<label for="coin-redeem-amount">¿Cuánto deseas canjear?</label><select id="coin-redeem-amount">${Array.from({length:Math.min(eligible/100,100)},(_,i)=>`<option value="${(i+1)*100}">${((i+1)*100).toLocaleString('es-MX',{style:'currency',currency:'MXN'})}</option>`).join('')}</select><label for="coin-redeem-pin">PIN de autorización</label><input id="coin-redeem-pin" type="password" inputmode="numeric" autocomplete="off" maxlength="4" pattern="[0-9]{4}" placeholder="••••" aria-label="PIN de autorización"><button class="primary coin-redeem-button" data-action="coin-redeem"><span aria-hidden="true">✦</span> Canjear <span aria-hidden="true">→</span></button><p class="coin-shop-message" role="status" aria-live="polite">${coinShopMessage||'El canje solo queda registrado en este dispositivo. Un adulto debe confirmar y entregar el dinero.'}</p>`:''}${history.length?`<section class="coin-history"><h2>Canjes registrados</h2><ol>${history.slice().reverse().map(item=>`<li><b>${item.amount.toLocaleString('es-MX',{style:'currency',currency:'MXN'})}</b><time>${new Date(item.at).toLocaleDateString('es-MX')}</time></li>`).join('')}</ol></section>`:''}</section>`;}
function gameHud(){return `<div class="game-hud"><div class="hud-top"><div class="hud-counters"><button class="hud-coins" data-action="coin-shop" title="Abrir canje de monedas" aria-label="Monedas: ${coinBalance.toLocaleString('es-MX')}. Abrir canje">${goldCoinIcon()} <b>${coinBalance.toLocaleString('es-MX')}</b></button><span class="hud-stars">⭐ <b>${totalStars()}</b></span><button class="hud-round" data-action="sound" aria-label="${muted?'Activar':'Desactivar'} sonido">${muted?'♪ ×':'♪ ✓'}</button></div></div><div class="hud-tools"><button data-action="dictionary" aria-label="Abrir diccionario"><span>▤</span><b>Diccionario</b></button><button data-action="collection" aria-label="Abrir mis cartas"><span>✧</span><b>Mis cartas</b></button></div><button class="hud-coral" data-ocean="mascot" aria-label="Saludar a Coral">${animal('turtle')}<span>¡Hola, Ximena!</span></button></div>`;}
function audioSettingsView(){return `${header('Sonidos de la aventura','DALE VIDA A TU OCÉANO')}<div class="audio-settings"><p>Olas tranquilas, música suave y una sorpresa en cada toque.</p><button class="primary" data-action="sound">${muted?'♪ Activar sonido':'♪ Silenciar todo'}</button>${[['effects','Efectos','Botones, animales, aciertos y premios'],['ambience','Océano','Olas y pequeños sonidos del paisaje'],['music','Música','Melodía suave de exploración']].map(([key,label,hint])=>`<label class="audio-slider"><span><b>${label}</b><small>${hint}</small></span><output>${Math.round(SoundWorld.volumes[key]*100)}%</output><input type="range" min="0" max="100" step="1" value="${Math.round(SoundWorld.volumes[key]*100)}" data-volume="${key}" aria-label="Volumen de ${label}"></label>`).join('')}<small class="audio-note">Tus volúmenes se recuerdan en este dispositivo. Activa el sonido con ♪ para empezar.</small></div>`;}
function render(){
 if(screen!=='adventure'){cancelGameTurn();adventure=null;}
 if(screen==='adventure'&&document.querySelector('.island-game')){updateAdventure();return;}
 closeMarineEncounter(false);
 const previousFocus=document.activeElement;
 const islandScreen=screen==='adventure'||screen==='locked';
 const keepMap=!islandScreen&&Boolean(document.querySelector('.world-app > .full-map .map-viewport'));
 clearRoomPrize();
 if(!keepMap)unmountMap();
 const outgoing=keepMap?document.querySelector('.overlay-shade'):root;
 outgoing?.getAnimations({subtree:true}).forEach(animation=>animation.cancel());
 document.querySelectorAll('.touch-particle,.touch-ring').forEach(el=>{el.getAnimations().forEach(animation=>animation.cancel());el.remove();});
 document.documentElement.dataset.theme=theme;
 document.documentElement.dataset.screen=screen;
 const views={locked:lockedIslandView,game:gameView,dictionary:dictionaryView,collection:islandCollectionView,adventure:adventureView,profile:profileView,reward:rewardView,'audio-settings':audioSettingsView,'coin-shop':coinShopView,'route-gate':luceroGateView};
 const overlayMarkup=screen!=='map'?`<div class="overlay-shade"><section class="screen-overlay" role="dialog" aria-modal="true" aria-label="${{locked:'Isla bloqueada',adventure:'Juegos de la isla',game:'Encuentra al animal',dictionary:'Diccionario',collection:'Mis cartas',profile:'Perfil',reward:'Recompensa','audio-settings':'Sonidos de la aventura','coin-shop':'Canje de monedas','route-gate':'Los caminos de Lucero'}[screen]}"><button class="overlay-audio" data-action="sound" aria-label="${muted?'Activar':'Silenciar'} sonido">${muted?'♪ ×':'♪ ✓'}</button><button class="overlay-close" data-action="map" aria-label="Cerrar y volver al mapa">✕</button>${screen==='game'?'<button class="overlay-dictionary" data-action="dictionary">▤ Diccionario</button>':''}${views[screen]()}</section></div>`:'';
 if(keepMap){
  const app=document.querySelector('.world-app'),map=app.querySelector('.full-map'),hud=app.querySelector('.hud-container');
  map.inert=screen!=='map';hud.inert=screen!=='map';
  const nextHud=document.createElement('div');nextHud.className='hud-container';nextHud.inert=hud.inert;nextHud.innerHTML=gameHud();patchGameNode(hud,nextHud);
  app.querySelector('.overlay-shade')?.remove();if(overlayMarkup)app.insertAdjacentHTML('beforeend',overlayMarkup);
 }else{
  root.innerHTML=`<div class="world-app">${islandScreen?'':`<div class="full-map" ${screen!=='map'?'inert':''}>${mapView()}</div><div class="hud-container" ${screen!=='map'?'inert':''}>${gameHud()}</div>`}${overlayMarkup}</div><div id="toast" role="status"></div>`;
 }
 decorateOcean(!keepMap);SoundWorld.sync();syncIslandRoom();syncMemoryText();
 if(screen!=='map')document.querySelector('.overlay-close').focus({preventScroll:true});
 else if(previousFocus?.closest('.screen-overlay'))document.querySelector('.map-viewport').focus({preventScroll:true});
}
document.addEventListener('keydown',event=>{
 const dialog=document.querySelector('.screen-overlay');if(!dialog)return;
 if(event.key==='Escape'){screen='map';render();return;}
 if(event.key==='Tab'){const items=[...dialog.querySelectorAll('button:not(:disabled), input, [tabindex="0"]'),...document.querySelectorAll('.app-update button:not(:disabled)')].filter(el=>el.getClientRects().length);const first=items[0],last=items.at(-1);if(event.shiftKey&&document.activeElement===first){event.preventDefault();last.focus();}else if(!event.shiftKey&&document.activeElement===last){event.preventDefault();first.focus();}}
});
function tone(success=true){SoundWorld.play(success?'tap':'wrong');}
root.addEventListener('contextmenu',event=>{
 if(!islandDevSettings.rightClickEntry||islandTravelActive||screen!=='map')return;
 const target=event.target.closest('.map-node,.island-hit,.scenic-island');
 if(!target)return;
 const index=target.matches('.scenic-island')?oceanIslands.findIndex(island=>island.type===target.dataset.island):Number(target.dataset.island);
 if(index<0||!oceanIslands[index])return;
 event.preventDefault();
 enterIsland(index,'game',true);
});
function resetGame(){startAdventure(1);}
root.addEventListener('click',event=>{const button=event.target.closest('button,a[data-action]');if(!button||button.dataset.ocean||islandTravelActive)return;if(screen==='map'&&(button.dataset.island!==undefined||button.dataset.action==='game')){enterIsland(Number(button.dataset.island??1),button.dataset.action);return;}if(button.dataset.luceroRoute!==undefined){unlockLuceroRoute(Number(button.dataset.luceroRoute));return;}if(button.dataset.play){handleAdventure(button);return;}if(button.dataset.lesson!==undefined){startAdventure(Number(button.dataset.lesson));render();return;}if(button.dataset.ui==='messi'||button.dataset.ui==='new-islands'){document.querySelector('.map-viewport').dispatchEvent(new CustomEvent('visit-landmark',{detail:button.dataset.ui==='messi'?'football':'chess'}));return;}if(button.dataset.ui==='mission'){missionCollapsed=!missionCollapsed;const mission=button.closest('.hud-mission');mission.classList.toggle('collapsed',missionCollapsed);button.setAttribute('aria-expanded',String(!missionCollapsed));button.querySelector('b').textContent=missionCollapsed?'+':'−';return;}if(button.tagName==='A')event.preventDefault();if(button.dataset.theme){theme=button.dataset.theme;render();return;}if(button.dataset.answer&&!selected){selected=button.dataset.answer;const good=selected===words[question].kind;if(good)correct++;else hearts--;feedback=good?`¡Muy bien! ${words[question].en} significa ${words[question].es.toLowerCase()}.`:hearts===0?'Se acabaron las vidas. ¡Vamos a practicar otra vez!':`${words[question].en} significa ${words[question].es.toLowerCase()}. Mira las imágenes y sigue aprendiendo.`;SoundWorld.play(good?'correct':hearts===0?'lose':'wrong');render();if(good){setTimeout(()=>{if(question===3){screen='reward';SoundWorld.play('win');}else{question++;selected=null;feedback='';}render();},900);}return;}const action=button.dataset.action;if(action==='route-gate'){openLuceroGate();return;}else if(action==='coin-shop'){coinShopMessage='';screen='coin-shop';}else if(action==='coin-redeem'){
 const input=document.querySelector('#coin-redeem-pin'),amount=Number(document.querySelector('#coin-redeem-amount')?.value),available=Math.floor(coinBalance/3000)*100;
 if(input?.value!==COIN_REDEEM_PIN)coinShopMessage='El PIN no es correcto.';
 else if(!Number.isSafeInteger(amount)||amount<100||amount%100!==0||amount>available)coinShopMessage='Selecciona un monto disponible en bloques de $100.';
 else{const coins=amount*30;if(coins>coinBalance)coinShopMessage='No hay suficientes monedas para ese monto.';else{const saved=spendCoins(coins);let history=coinRedemptions();history.push({amount,at:new Date().toISOString()});try{localStorage.setItem(COIN_REDEMPTIONS_KEY,JSON.stringify(history));coinShopMessage=`Canje de ${amount.toLocaleString('es-MX',{style:'currency',currency:'MXN'})} registrado${saved?'':' en esta sesión'}.`;}catch{coinShopMessage='Se descontaron las monedas, pero no se pudo guardar el registro.';}}}
 screen='coin-shop';
}else if(action==='sound'){SoundWorld.toggle();}else if(action==='game')resetGame();else if(action==='next'){if(!hearts){SoundWorld.play('retry');resetGame();}else if(question===3){screen='reward';SoundWorld.play('win');}else{SoundWorld.play('tap');question++;selected=null;feedback='';}}else if(action==='flip'){button.classList.toggle('flipped');return;}else if(action==='preview'){const toast=document.querySelector('#toast');toast.textContent='Esta vista previa incluye Animales del mar. Los demás mundos llegarán después.';toast.classList.add('show');setTimeout(()=>toast.classList.remove('show'),3500);return;}else if(action==='select-profile'){tone();button.classList.add('selected');return;}else if(['map','dictionary','collection','profile','audio-settings'].includes(action))screen=action;render();});
root.addEventListener('input',event=>{if(event.target.dataset.volume){SoundWorld.setVolume(event.target.dataset.volume,Number(event.target.value)/100);event.target.closest('label').querySelector('output').value=event.target.value+'%';return;}if(event.target.id==='search'){filter=event.target.value;document.querySelector('#word-grid').innerHTML=wordCards();}});
render();
